# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: pg
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: users-isleofcode
  host: localhost
  pool: 5
  username: postgres
  password: Brandon1997

test:
  adapter: postgresql
  encoding: unicode
  database: users-isleofcode-test
  host: localhost
  pool: 5
  username: postgres
  password: Brandon1997

production:
  adapter: postgresql
  encoding: unicode
  database: users-isleofcode-production
  host: localhost
  pool: 5
  username: postgres
  password: Brandon1997
